version: '3'

services:
  nodejs:
    build: .
    ports:
      - "80:8080"
    networks:
      - app-network
  db:
    image: mongo:4.2
    container_name: mongo
    ports:
      - "3333:27017"
    volumes:
      - dbdata:/data/db
    networks:
      - app-network

networks:
  app-network:

volumes:
  dbdata: